### ISSUE TITLE
Needs graphics

### ISSUE THREAD

**Issue by mvriel** [WeCamp/UnderTreasure#2]
[undertreasure.zip](https://github.com/WeCamp/UnderTreasure/files/434817/undertreasure.zip)

**Comment by mvriel** [comment]
![kaart](https://cloud.githubusercontent.com/assets/193704/17933017/be8fd81a-6a12-11e6-9c96-cbd1d2e52f95.png)

**Comment by ivstefano** [comment]
The issue was resolved, we have a very nice overlay now :)
